version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        container_name: health_tech_postgres
        environment:
            POSTGRES_USER: youruser
            POSTGRES_PASSWORD: yourpassword
            POSTGRES_DB: yourdbname
        ports:
            - '5432:5432'
        volumes:
            - health_tech_postgres_data:/var/lib/postgresql/data

volumes:
    health_tech_postgres_data:
